### ISSUE TITLE
Using a MarkerFile as a target for a task

### ISSUE THREAD

**Issue by barryskal** [helix-collective/dnit-utils#7]
I have the following task that creates a docker image:

```
  const marker: MarkerFile = new MarkerFile(path.join(ROOT, name, ".dockerfile"));
  return task({
    name: `${name}Image`,
    description: `Build a docker image for ${name}`,
    action: async () => {
      await runConsole([
        "docker",
        "build",
        "-t",
        `${name}`,
        "--platform",
        "linux/amd64",
        "-f",
        path.join(
          "infrastructure",
          "instances",
          `${dockerFileName}.Dockerfile`,
        ),
        ".",
        "--compress",
      ], {
        cwd: path.join(ROOT, name),
      });
      await marker.action();
    },
    deps: [
      buildTask,
    ],
    targets: [
      marker,
    ],
  });
```

However when I try to run dnit I get the following error:
```
TS2322 [ERROR]: Type 'MarkerFile' is not assignable to type 'TrackedFile'.
    marker,
    ~~~~~~~~~~~~~~~~~~~~~
    at file:///blah/dnit/testing.ts:30:5
```

This is really confusing because MarkerFile extends TrackedFile so I don't see why I should be getting this error. 

Modifying the target as so fixes the breakage

```
      (marker as unknown) as TrackedFile,
```

Not ideal though

**Comment by paul-thompson-helix** [comment]
It's probably because of versions of dnit that are being imported - could be one you're importing directly and another coming in via this dnit-utils.

**Comment by paul-thompson-helix** [comment]
Tests ok within itself - https://github.com/helix-collective/dnit-utils/pull/8

Check using `deno info` that you're not getting two different versions of dnit being pulled in.

**Comment by barryskal** [comment]
Confirmed, it was because of two different versions. Closing this issue
